[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='0x3a92ae47d9a1844005ea9848e44fba905e4c3516301cc58e8281d05c21dd9cac'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
